# Generated by Django 6.0.5 on 2026-05-24 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata_code', models.CharField(help_text='IATA 3-letter code', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('FUEL', 'Fuel Combustion'), ('ELECTRICITY', 'Purchased Electricity'), ('FLIGHT', 'Business Travel - Flights'), ('HOTEL', 'Business Travel - Hotel Stays'), ('GROUND_TRANSPORT', 'Business Travel - Ground Transport')], max_length=50)),
                ('activity_type', models.CharField(help_text='e.g. DIESEL, LPG, GRID_ELECTRICITY, FLIGHT_SHORT_HAUL, HOTEL_NIGHT', max_length=100)),
                ('region', models.CharField(default='GLOBAL', help_text='e.g. US-CA, DE, GB, GLOBAL', max_length=50)),
                ('factor', models.DecimalField(decimal_places=6, help_text='kg CO2e per unit', max_digits=15)),
                ('unit', models.CharField(help_text='Standard unit e.g. L, kWh, pkm, room_night', max_length=20)),
                ('source_citation', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL_PROCUREMENT', 'SAP Fuel & Procurement'), ('UTILITY_PORTAL_CSV', 'Utility Portal CSV'), ('CONCUR_TRAVEL', 'Concur/Navan Travel Export')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hq_country', models.CharField(default='US', help_text='ISO 2-letter country code', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField(help_text='Row index in original file')),
                ('raw_data', models.JSONField(help_text='Original raw record as JSON')),
                ('status', models.CharField(choices=[('SUCCESS', 'Successfully Normalized'), ('FAILED', 'Failed Parsing/Validation'), ('SKIPPED', 'Skipped (Non-Emissions)')], default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='esg_ingest.ingestionjob')),
            ],
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='esg_ingest.tenant'),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('plant_code', models.CharField(help_text='SAP Plant Code (WERKS)', max_length=50)),
                ('country', models.CharField(help_text='ISO 2-letter country code', max_length=2)),
                ('region', models.CharField(help_text='State/Province or Grid Subregion', max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='esg_ingest.tenant')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'unique_together': {('tenant', 'plant_code')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor'), ('ADMIN', 'Admin')], default='ANALYST', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='esg_ingest.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(max_length=50)),
                ('activity_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('raw_unit', models.CharField(max_length=20)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('normalized_unit', models.CharField(max_length=20)),
                ('carbon_emissions_mtco2e', models.DecimalField(decimal_places=6, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analyst Sign-off'), ('APPROVED', 'Approved & Locked'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='esg_ingest.facility')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='esg_ingest.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='esg_ingest.tenant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to='esg_ingest.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esg_ingest.userprofile'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated/Edited'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='esg_ingest.normalizedrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='esg_ingest.tenant')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esg_ingest.userprofile')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UtilityAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=100)),
                ('meter_number', models.CharField(max_length=100)),
                ('provider_name', models.CharField(max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_accounts', to='esg_ingest.facility')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_accounts', to='esg_ingest.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'meter_number')},
            },
        ),
    ]
